driver:
  name: ec2
  aws_ssh_key_id: mdas-key
  region: us-east-1
  availability_zone: e
  subnet_id: subnet-8d9ddbb1
  instance_type: t2.micro
  image_id: ami-49c9295f
  security_group_ids: sg-215f685e
  retryable_tries: 120

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  ssh_key: /home/ubuntu/.ssh/mdas.pem

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[test1::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
